framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            marketing_bus:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    # for AMQP send to a separate exchange then queue
                    exchange:
                        name: marketing.exchange
                    queues:
                        marketing.queue: ~
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    # for AMQP send to a separate exchange then queue
                    exchange:
                        name: marketing.failed
                    queues:
                        marketing.failed: ~

        routing:
            # Route your messages to the transports
            'App\Message\SmsNotification': marketing_bus
